Testes relacionamentos models
LeonardoGomes99/laravel-training pull request #2
Opened 2022-04-11 23:42 UTC by LeonardoGomes99

Testes de relacionamentos entre as models

2022-04-18 15:37 UTC, csaraugustol commented on tests/Feature/BookTest.php
> +        $book = factory(Book::class)->create();
Criar o cenário para ter comentários

2022-04-18 15:37 UTC, csaraugustol commented on tests/Feature/BookTest.php
> +        $book = factory(Book::class)->create();
Criar o cenário para ter sugestões

2022-04-18 15:37 UTC, csaraugustol commented on tests/Feature/BookTest.php
> +        $book = factory(Book::class)->create();
Criar o cenário para ter tag

2022-04-18 15:37 UTC, csaraugustol commented on tests/Feature/CategoryTest.php
> +        $category = factory(Category::class)->create();
Criar o cenário para a Category estar vinculada a uma BookCategory

2022-04-18 15:37 UTC, csaraugustol commented on tests/Feature/CommentTest.php
> +            $comment->book->first()
Remover o first()

2022-04-18 15:37 UTC, csaraugustol commented on tests/Feature/PublisherTest.php
> +        $publisher = factory(Publisher::class)->create();
Criar o cenário para vincular livros a publicação

2022-04-18 15:37 UTC, csaraugustol commented on tests/Feature/PublisherTest.php
> +            $publisher->book
O correto seria $publisher->books

2022-04-18 15:37 UTC, csaraugustol commented on tests/Feature/SuggestionTest.php
> +            $suggestion->book->first()
Remover o first()

2022-04-18 15:37 UTC, csaraugustol commented on tests/Feature/TagTest.php
> +            $tag->book->first()
Remover o first()

2022-04-19 14:59 UTC, eduardohenriquesousasilva requested changes
Adicionei alguns comentários, poderia verificar por favor? Qualquer dúvida fique a vontade para entrar em contato

2022-04-19 14:59 UTC, eduardohenriquesousasilva commented on tests/Integration/Models/BookTest.php
> +        );
Adicioanar o assert pra ver se os itens dentro da collection são do tipo de dado esperado no caso BookCategory

2022-04-19 14:59 UTC, eduardohenriquesousasilva commented on tests/Integration/Models/BookTest.php
> +        $this->assertInstanceOf(
Adicionar uma assertion para verificar se o itens dentro da collection são do tipo Tag

2022-04-19 19:35 UTC, LeonardoGomes99 commented on tests/Integration/Models/PublisherTest.php
> +        $this->assertInstanceOf(
Refatorado

2022-04-19 19:35 UTC, LeonardoGomes99 commented on tests/Integration/Models/CategoryTest.php
> +            $category->booksCategories
Refatorado

2022-04-19 19:35 UTC, LeonardoGomes99 commented on tests/Integration/Models/BookTest.php
> +        $this->assertInstanceOf(
Refatorado

2022-04-19 19:35 UTC, LeonardoGomes99 commented on tests/Integration/Models/BookTest.php
> +            $book->suggestions
Refatorado, Observação: No Caso seria Tipo Suggestion*

2022-04-19 19:35 UTC, LeonardoGomes99 commented on tests/Integration/Models/BookTest.php
> +        );
Refatorado

2022-04-19 19:35 UTC, LeonardoGomes99 commented on tests/Integration/Models/BookTest.php
> +        );
Refatorado

2022-04-19 19:35 UTC, LeonardoGomes99 commented on tests/CreatesApplication.php
> +{
Adicionado a Importação DatabaseTransactions.

2022-04-20 02:09 UTC, LeonardoGomes99 commented on tests/Integration/Models/BookTest.php
> +use App\Models\BookCategory;
refatorado

2022-04-20 02:09 UTC, LeonardoGomes99 commented on tests/Integration/Models/CommentTest.php
> +            $comment->book->first()
refatorado

2022-04-20 02:09 UTC, LeonardoGomes99 commented on tests/Integration/Models/BookTest.php
> +            $book->publisher->first()
refatorado

2022-04-20 12:37 UTC, csaraugustol commented on app/Models/Book.php
> +        'id' => 'string',
Alinhar as chaves '=>'

2022-04-20 12:37 UTC, csaraugustol commented on app/Models/BookCategory.php
> +        'id' => 'string',
Alinhar as chaves '=>'

2022-04-20 12:37 UTC, csaraugustol commented on app/Models/Category.php
> +        'id' => 'string',
Alinhar as chaves '=>'

2022-04-20 12:37 UTC, csaraugustol commented on app/Models/Comment.php
> +        'id' => 'string',
Alinhar as chaves '=>'

2022-04-20 12:37 UTC, csaraugustol commented on app/Models/Publisher.php
> +        'id' => 'string',
Alinhar as chaves '=>'

2022-04-20 12:37 UTC, csaraugustol commented on app/Models/Suggestion.php
> +        'id' => 'string',
Alinhar as chaves '=>'

2022-04-20 12:37 UTC, csaraugustol commented on app/Models/Tag.php
> +        'id' => 'string',
Alinhar as chaves '=>'

2022-04-20 13:02 UTC, csaraugustol commented on tests/Integration/Models/BookCategoryTest.php
> +use Illuminate\Foundation\Testing\RefreshDatabase;
Remover os imports que não estão sendo usados

2022-04-20 13:02 UTC, csaraugustol commented on tests/Integration/Models/BookTest.php
> +use Illuminate\Foundation\Testing\RefreshDatabase;
Remover os imports que não estão sendo usados

2022-04-20 14:29 UTC, LeonardoGomes99 commented on tests/Integration/Models/BookTest.php
> +use Illuminate\Foundation\Testing\RefreshDatabase;
refatorado

2022-04-20 14:29 UTC, LeonardoGomes99 commented on tests/Integration/Models/BookCategoryTest.php
> +use Illuminate\Foundation\Testing\RefreshDatabase;
refatorado

2022-04-20 14:30 UTC, LeonardoGomes99 commented on tests/Integration/Models/TagTest.php
> +use Illuminate\Foundation\Testing\RefreshDatabase;
refatorado

2022-04-20 14:30 UTC, LeonardoGomes99 commented on tests/Integration/Models/PublisherTest.php
> +use Illuminate\Foundation\Testing\RefreshDatabase;
refatorado

2022-04-20 14:30 UTC, LeonardoGomes99 commented on tests/Integration/Models/CommentTest.php
> +use Illuminate\Foundation\Testing\RefreshDatabase;
refatorado

2022-04-20 14:30 UTC, LeonardoGomes99 commented on tests/Integration/Models/SuggestionTest.php
> +use Illuminate\Foundation\Testing\WithFaker;
refatorado

2022-04-20 14:30 UTC, LeonardoGomes99 commented on tests/Integration/Models/CategoryTest.php
> +use Illuminate\Foundation\Testing\RefreshDatabase;
refatorado

2022-04-20 14:30 UTC, LeonardoGomes99 commented on app/Models/Publisher.php
> +        'id' => 'string',
refatorado

2022-04-20 14:31 UTC, LeonardoGomes99 commented on app/Models/Comment.php
> +        'id' => 'string',
refatorado

2022-04-20 14:31 UTC, LeonardoGomes99 commented on app/Models/Category.php
> +        'id' => 'string',
refatorado

2022-04-20 14:31 UTC, LeonardoGomes99 commented on app/Models/BookCategory.php
> +        'id' => 'string',
refatorado

2022-04-20 14:31 UTC, LeonardoGomes99 commented on app/Models/Book.php
> +        'id' => 'string',
refatorado

2022-04-20 16:54 UTC, LeonardoGomes99 commented on tests/Integration/Models/BookTest.php
> +        $booksCategories = factory(BookCategory::class)->create([
refatorado

2022-04-20 16:54 UTC, LeonardoGomes99 commented on tests/Integration/Models/CategoryTest.php
> +        $bookCategories = factory(BookCategory::class)->create([
refatorado

2022-04-20 16:54 UTC, LeonardoGomes99 commented on tests/Integration/Models/PublisherTest.php
> +        $books = factory(Book::class)->create([
refatorado

2022-04-20 16:54 UTC, LeonardoGomes99 commented on tests/TestCase.php
> +use Illuminate\Foundation\Testing\DatabaseTransactions;
refatorado

2022-04-25 13:41 UTC, eduardohenriquesousasilva approved these changes
Me parece ok o PR com todas as modificações atendidas

2022-04-25 13:47 UTC, merged